2023-05-21 17:30:09,038 ERROR Internal Server Error: /articles/create/ A:\DjangoProjects\venv\lib\site-packages\django\utils\log.py
Traceback (most recent call last):
  File "A:\DjangoProjects\venv\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "A:\DjangoProjects\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "A:\DjangoProjects\venv\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "A:\DjangoProjects\venv\lib\site-packages\django\contrib\auth\mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "A:\DjangoProjects\venv\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "A:\DjangoProjects\venv\lib\site-packages\django\views\generic\edit.py", line 184, in post
    return super().post(request, *args, **kwargs)
  File "A:\DjangoProjects\venv\lib\site-packages\django\views\generic\edit.py", line 153, in post
    return self.form_valid(form)
  File "A:\DjangoProjects\NewsPaper\NPbd\views.py", line 79, in form_valid
    return super().form_valid(form)
  File "A:\DjangoProjects\venv\lib\site-packages\django\views\generic\edit.py", line 136, in form_valid
    return super().form_valid(form)
  File "A:\DjangoProjects\venv\lib\site-packages\django\views\generic\edit.py", line 65, in form_valid
    return HttpResponseRedirect(self.get_success_url())
  File "A:\DjangoProjects\venv\lib\site-packages\django\views\generic\edit.py", line 125, in get_success_url
    url = self.object.get_absolute_url()
  File "A:\DjangoProjects\NewsPaper\NPbd\models.py", line 50, in get_absolute_url
    1/0
ZeroDivisionError: division by zero
2023-05-21 17:30:09,047 ERROR "POST /articles/create/ HTTP/1.1" 500 112330 A:\DjangoProjects\venv\lib\site-packages\django\core\servers\basehttp.py
2023-05-21 17:55:12,973 ERROR Internal Server Error: /articles/create/ A:\DjangoProjects\venv\lib\site-packages\django\utils\log.py
Traceback (most recent call last):
  File "A:\DjangoProjects\venv\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "A:\DjangoProjects\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "A:\DjangoProjects\venv\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "A:\DjangoProjects\venv\lib\site-packages\django\contrib\auth\mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "A:\DjangoProjects\venv\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "A:\DjangoProjects\venv\lib\site-packages\django\views\generic\edit.py", line 184, in post
    return super().post(request, *args, **kwargs)
  File "A:\DjangoProjects\venv\lib\site-packages\django\views\generic\edit.py", line 153, in post
    return self.form_valid(form)
  File "A:\DjangoProjects\NewsPaper\NPbd\views.py", line 79, in form_valid
    return super().form_valid(form)
  File "A:\DjangoProjects\venv\lib\site-packages\django\views\generic\edit.py", line 136, in form_valid
    return super().form_valid(form)
  File "A:\DjangoProjects\venv\lib\site-packages\django\views\generic\edit.py", line 65, in form_valid
    return HttpResponseRedirect(self.get_success_url())
  File "A:\DjangoProjects\venv\lib\site-packages\django\views\generic\edit.py", line 125, in get_success_url
    url = self.object.get_absolute_url()
  File "A:\DjangoProjects\NewsPaper\NPbd\models.py", line 50, in get_absolute_url
    1/0
ZeroDivisionError: division by zero
2023-05-21 17:55:13,085 ERROR "POST /articles/create/ HTTP/1.1" 500 145 A:\DjangoProjects\venv\lib\site-packages\django\core\servers\basehttp.py
2023-05-21 18:08:56,052 ERROR Internal Server Error: /articles/create/ A:\DjangoProjects\venv\lib\site-packages\django\utils\log.py
Traceback (most recent call last):
  File "A:\DjangoProjects\venv\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "A:\DjangoProjects\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "A:\DjangoProjects\venv\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "A:\DjangoProjects\venv\lib\site-packages\django\contrib\auth\mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "A:\DjangoProjects\venv\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "A:\DjangoProjects\venv\lib\site-packages\django\views\generic\edit.py", line 184, in post
    return super().post(request, *args, **kwargs)
  File "A:\DjangoProjects\venv\lib\site-packages\django\views\generic\edit.py", line 153, in post
    return self.form_valid(form)
  File "A:\DjangoProjects\NewsPaper\NPbd\views.py", line 79, in form_valid
    return super().form_valid(form)
  File "A:\DjangoProjects\venv\lib\site-packages\django\views\generic\edit.py", line 136, in form_valid
    return super().form_valid(form)
  File "A:\DjangoProjects\venv\lib\site-packages\django\views\generic\edit.py", line 65, in form_valid
    return HttpResponseRedirect(self.get_success_url())
  File "A:\DjangoProjects\venv\lib\site-packages\django\views\generic\edit.py", line 125, in get_success_url
    url = self.object.get_absolute_url()
  File "A:\DjangoProjects\NewsPaper\NPbd\models.py", line 50, in get_absolute_url
    1/0
ZeroDivisionError: division by zero
2023-05-21 18:08:56,098 ERROR "POST /articles/create/ HTTP/1.1" 500 145 A:\DjangoProjects\venv\lib\site-packages\django\core\servers\basehttp.py
